version: "3"
services:
  web:
    image: ${REGISTRY}/${IMAGE}.com:latest
    ports:
      - "80:80"
    networks:
      - magick8sball
    volumes:
      - ${PWD}/_site:/srv
      - ${PWD}/Caddyfile.dev:/etc/Caddyfile
  api:
    image: ${REGISTRY}/${IMAGE}:${TAG}
    ports:
      - "8080:8080"
    networks:
      - magick8sball
networks:
  magick8sball:
